# Generated by Django 5.2.8 on 2025-11-27 15:05

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='Rizal', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
                ('given_name', models.CharField(default='Jose', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
                ('middle_initial', models.CharField(default='P.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='Rizal', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
                ('given_name', models.CharField(default='Jose', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
                ('middle_initial', models.CharField(default='P.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'No symbols are allowed except ".".')])),
                ('birth_date', models.CharField(blank=True, default=datetime.date(1, 1, 1), null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('date_booked', models.DateField(default=datetime.date(1, 1, 1))),
                ('date_expiration', models.DateField(default=datetime.date(1, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='S-000', max_length=5, validators=[django.core.validators.RegexValidator('^[AS]-[0-9][0-9][0-9]$', 'Must follow the format "A-###" or "S-###".')])),
                ('max_speed', models.PositiveIntegerField(default=0)),
                ('no_of_seats', models.PositiveIntegerField(default=0)),
                ('no_of_toilets', models.PositiveIntegerField(default=0)),
                ('has_recling_seats', models.BooleanField(default=False)),
                ('has_folding_tables', models.BooleanField(default=False)),
                ('has_disability_access', models.BooleanField(default=False)),
                ('has_luggage_storage', models.BooleanField(default=False)),
                ('has_vending_machines', models.BooleanField(default=False)),
                ('has_food_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('travel_time', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('route_type', models.CharField(choices=[('INT', 'Inter-town'), ('LOC', 'Local')], default='INT')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_route_destinations', to='main.station')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_route_origins', to='main.station')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('task', models.CharField(default='General Maintenance', max_length=255)),
                ('condition', models.CharField(choices=[('worse', 'Worse'), ('bad', 'Bad'), ('good', 'Good'), ('vgood', 'Very Good'), ('excellent', 'Excellent')], default='good', max_length=50)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crewmember')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.train')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('departure_time'), '-', models.F('arrival_time')), output_field=models.DurationField())),
                ('trip_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_trip_destinations', to='main.station')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_trip_origins', to='main.station')),
            ],
        ),
    ]
