# Generated by Django 5.2.8 on 2025-11-27 16:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['surname']},
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='given_name',
            field=models.CharField(default='Jose', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='middle_initial',
            field=models.CharField(default='P.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='surname',
            field=models.CharField(default='Rizal', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='given_name',
            field=models.CharField(default='Jose', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_initial',
            field=models.CharField(default='P.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='Rizal', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z. ]*$', 'No symbols are allowed except ".".')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('INT', 'Inter-town'), ('LOC', 'Local')], default='LOC'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='Unnamed Station', max_length=255),
        ),
    ]
