# Generated by Django 5.2.8 on 2025-11-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_options_alter_crewmember_given_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceevent',
            options={'ordering': ['-event_date']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trips',
            field=models.ManyToManyField(to='main.trip'),
        ),
    ]
