# Generated by Django 5.2.8 on 2025-11-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_maintenanceevent_options_ticket_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-trip_date']},
        ),
        migrations.AddField(
            model_name='trip',
            name='assigned_train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.train'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.route'),
        ),
    ]
