# Generated by Django 5.2.8 on 2025-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ticket_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='owner',
            new_name='passenger',
        ),
    ]
